Added my card to the scrollodex
wwcodecolorado/scrollodex pull request #134
Opened 2022-10-21 21:54 UTC by cassreinhart

# Summary of changes
Added Cassandra Reinhart's card-- follow me on Github and connect on LinkedIn!

# Related Issue

# How to test (for features) / reproduce (for bugs)

# Screenshots

# Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Documentation (explains but does not affect functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Notes
- please consider including a gif that reflects your feelings about this PR
![hyped](https://media.giphy.com/media/4GaHBQh3f4jBEpbQvP/giphy.gif)

2022-10-22 18:39 UTC, jischr requested changes
great card! just a small update requested.

2022-10-22 18:39 UTC, jischr commented on .gitignore
> -# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
did you remove these by accident?

2022-10-23 19:27 UTC, cassreinhart reviewed
Let me know if my changes resolved the issue!

2022-10-23 23:49 UTC, jischr approved these changes
Looks great!

2022-10-23 23:49 UTC, merged